// 预览不接入登录、支付或 AI 服务，只展示与设计稿一致的内容和跳转。
const fs=require('fs'),path=require('path'),dir=__dirname;
const design=JSON.parse(fs.readFileSync(path.join(dir,'design.json')));
const {palette,padding,widths,cardModel}=require('./layout');
fs.mkdirSync(path.join(dir,'assets'),{recursive:true});
for(const key of Object.keys(design.state.images))fs.copyFileSync('/private/tmp/pet-figma-assets/'+key+'.jpg',path.join(dir,'assets',key+'.jpg'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(n,w){
 let attr=`data-key="${n.key||''}"`,css=`width:${w}px;flex-shrink:0;`;
 if(n.type==='text')return `<div ${attr} style="${css}font-size:${n.size}px;line-height:1.5;font-weight:${n.bold?700:400};color:#${palette[n.color||'ink']};${n.serif?'font-family:Songti SC,serif;':''}letter-spacing:${n.tracking||0}px">${esc(n.text)}</div>`;
 if(n.type==='image')return `<img ${attr} src="assets/${n.image}.jpg" style="${css}height:${n.h}px;object-fit:cover;border-radius:${n.radius||0}px" alt="宠物实拍示例">`;
 if(n.type==='button')return `<button ${attr} ${n.target?`data-target="${n.target}"`:''} ${n.disabled?'disabled':''} class="${n.ghost?'ghost':n.secondary?'secondary':''}" style="${css}height:${n.h||48}px">${esc(n.text)}</button>`;
 if(n.type==='petcard')return `<a ${attr} ${n.target?`data-target="${n.target}"`:""} style="display:block;${css}">${render(cardModel(n),w)}</a>`;
 const pad=padding(n),ws=widths(n,w);
 css+=`display:flex;flex-direction:${n.dir==='HORIZONTAL'?'row':'column'};gap:${n.gap??16}px;padding:${pad.y}px ${pad.x}px;border-radius:${n.radius||0}px;${n.bg?`background:#${palette[n.bg]};`:''}${n.stroke?`outline:1px solid #${palette[n.stroke]};`:''}${n.center?'align-items:center;':''}${n.h?`min-height:${n.h}px;`:''}`;
 return `<div ${attr} style="${css}">${(n.children||[]).map((c,i)=>render(c,ws[i])).join('')}</div>`;
}
const sections=design.pages.map(s=>`<section id="${s.id}" data-device="${s.device}" style="width:${s.w}px"><div class="sheet-title">${esc(s.name)}</div>${render({...s,gap:0},s.w)}</section>`).join('');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>暖爪 · 三端设计预览</title><style>*{box-sizing:border-box}body{margin:0;background:#e8e4df;color:#2B2724;font-family:'PingFang SC',sans-serif}div{white-space:pre-wrap}header{position:sticky;top:0;z-index:9;background:#2B2724;color:white;padding:12px 24px;display:flex;gap:20px;align-items:center;font-size:13px}header a{color:#ffd5ba;cursor:pointer}select{padding:8px;max-width:380px}section{margin:24px auto;background:#FBF8F3;box-shadow:0 10px 40px #0001;display:none}section.active{display:block;animation:appear .3s ease-out}.sheet-title{padding:14px 24px;background:#f2ece2;font-size:13px;color:#746b63}button{border:0;border-radius:12px;background:#B9512B;color:white;font:500 15px 'PingFang SC',sans-serif;cursor:pointer;padding:0 12px;transition:background .18s,transform .18s}button:hover{background:#923C1F;transform:translateY(-1px)}button.secondary{background:#fff;border:1px solid #E4DBD0;color:#B9512B}button.ghost{background:transparent;color:#746B63}button.secondary:hover,button.ghost:hover{background:#F7E4D3}button:disabled{background:#E4DBD0;color:#746B63;cursor:default}a[data-target]{cursor:pointer}img{display:block}@keyframes appear{from{opacity:.4;transform:translateY(8px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}</style><header><b>暖爪 / 设计预览</b><a data-target="d-home">电脑买家端</a><a data-target="m-home">手机买家端</a><a data-target="a-home">管理后台</a><select id="pages">${design.pages.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><span>示例数据 · 表单和支付仅展示</span></header>${sections}<script>function show(id){const target=document.getElementById(id);if(!target)return;document.querySelectorAll('section').forEach(s=>s.classList.toggle('active',s===target));document.getElementById('pages').value=id;history.replaceState(null,'','#'+id);window.scrollTo(0,0)}document.addEventListener('click',e=>{const el=e.target.closest('[data-target]');if(el)show(el.dataset.target)});document.getElementById('pages').onchange=e=>show(e.target.value);show(location.hash.slice(1)||'d-home');</script></html>`;
fs.writeFileSync(path.join(dir,'preview.html'),html);
let links=0;const ids=new Set(design.pages.map(p=>p.id));function check(n){if(n.target){if(!ids.has(n.target))throw Error('Missing '+n.target);links++;}if(n.color&&!palette[n.color])throw Error('Invalid color');(n.children||[]).forEach(check);}design.pages.forEach(check);
console.log(JSON.stringify({screens:design.pages.length,validLinks:links,preview:'preview.html'}));
