/** 本地前端演示适配器。数据仅存在内存，重启即重置；禁止部署为生产后端。 */
import express from 'express'
import multer from 'multer'
import {randomUUID} from 'node:crypto'
const app=express(),api=express.Router(),now=()=>new Date().toISOString(),id=p=>p+'_'+randomUUID().slice(0,8)
app.use(express.json({limit:'1mb'}));app.use('/api/v1',api)
const ok=(res,data,status=200)=>res.status(status).json({code:'OK',message:'success',data,requestId:id('req'),serverTime:now()})
const fail=(res,message,status=422)=>res.status(status).json({code:status===401?'UNAUTHORIZED':'DEMO_VALIDATION',message,data:null})
const tokens=new Map(),users=new Map(),orders=[],sales=[],files=new Map(),sessions=[],jobs=new Map(),sms=new Map(),captchas=new Set(),replays=new Map()
const mask=p=>p.slice(0,3)+'****'+p.slice(-4)
let shop={id:'shop_1',name:'暖爪宠物生活馆',address:'杭州市西湖区文二路 188 号（演示地址）',phone:'0571-88886666',wechat:'WarmPawDemo',businessHours:'周一至周日 10:00–20:00',pickupInstructions:'请提前联系店主预约，携带本人手机与航空箱到店。',latitude:30.28,longitude:120.12,coordinateSystem:'gcj02',version:1,paymentTimeoutMinutes:30,pickupRetentionHours:72,exchangeEnabled:false,banners:[{id:'banner_1',title:'把心动，变成每天的陪伴。',imageFileId:'photo_corgi',linkType:'pet',petId:'pet_1',noticeText:null,sortOrder:0,enabled:true}]}
const specs=[['奶糖','dog','威尔士柯基犬','corgi',480000],['年糕','cat','英国短毛猫','cat',180000],['松饼','dog','金毛寻回犬','golden',360000],['橘子','cat','中华田园猫','ginger',150000],['布丁','cat','布偶猫','kitten',580000],['可可','dog','贵宾犬','puppy',280000]]
const pets=specs.map(([name,category,breed,photo,priceAmount],i)=>({id:`pet_${i+1}`,name,category,breed,priceAmount,currency:'CNY',coverUrl:`/images/${photo}.jpg`,gender:i%2?'female':'male',ageMonths:3+i,status:'on_sale',isRecommended:i<4,publishedAt:now(),version:1,weightKg:2.5+i,color:i%2?'奶油白':'暖棕',personalityTags:['亲人','活泼'],vaccineStatus:'演示记录：实际接种凭证须到店核验',dewormStatus:'演示记录：实际驱虫记录须到店核验',description:`我是${name}，正在等待一位耐心的新家人。喜欢玩耍，也喜欢安静地陪在你身旁。`,feedingNotes:'新到家请保持原有饮食，缓慢过渡，并准备安静、安全的休息空间。',healthDescription:'本页为演示个体，不代表实际健康核验结果。购买前请查阅真实检疫证明并现场检查。',images:[{fileId:`photo_${photo}`,url:`/images/${photo}.jpg`,sortOrder:0}],videoUrl:null,quarantine:null,imageFileIds:[`photo_${photo}`],videoFileId:null,birthDate:null,recommendationOrder:i,activeOrderId:null}))
for(const p of pets)files.set(p.imageFileIds[0],{id:p.imageFileIds[0],originalName:p.name+'.jpg',publicUrl:p.coverUrl,purpose:'pet_image'})
const categories=[{code:'cat',name:'猫咪',breeds:pets.filter(p=>p.category==='cat').map(p=>p.breed)},{code:'dog',name:'狗狗',breeds:pets.filter(p=>p.category==='dog').map(p=>p.breed)}]
// 管理档案转换为公开 DTO，证明仅包含允许公开的图片。
const publicPet=p=>({...p,quarantine:p.quarantine?{certificateNo:p.quarantine.certificateNo,validUntil:p.quarantine.validUntil,reviewStatus:'demo',images:(p.quarantine.publicImageFileIds||[]).map(i=>({fileId:i,url:files.get(i)?.publicUrl})).filter(i=>i.url)}:null,videoUrl:files.get(p.videoFileId)?.publicUrl||null,shop,purchaseAllowed:p.status==='on_sale',purchaseBlockedReason:p.status==='on_sale'?null:'这位小伙伴暂不可购买'})
const adminPet=p=>({...p,assets:p.imageFileIds.map(i=>files.get(i)).filter(Boolean)})
const agreement=type=>({id:'agreement_'+type,type,version:'demo-v1',title:type==='pickup_confirmation'?'到店健康确认书（演示）':'活体宠物交易须知（演示）',content:'【演示文本，不构成真实交易协议】\n1. 仅限购买人本人到店自提。\n2. 请现场核对身份、宠物个体、检疫凭证与健康状态。\n3. 演示保障期为交付后七天，健康问题应保留正规诊断报告并联系店主。\n4. 此环境不会发生真实支付、退款或短信发送。',contentHash:'demo-hash-'+type,healthGuaranteeDays:7})
const page=(list,q)=>{const p=Math.max(1,Number(q.page)||1),size=Math.min(100,Math.max(1,Number(q.pageSize)||12));return {items:list.slice((p-1)*size,p*size),page:p,pageSize:size,total:list.length}}
function filtered(list,q){let out=list.filter(p=>(!q.keyword||[p.name,p.breed,p.title,p.orderNo,p.content].join(' ').includes(q.keyword))&&(!q.orderNo||p.orderNo?.includes(q.orderNo))&&(!q.category||p.category===q.category)&&(!q.status||p.status===q.status)&&(!q.breed||p.breed===q.breed)&&(!q.gender||p.gender===q.gender)&&(!q.color||p.color?.includes(q.color)));for(const [key,field,cmp] of [['minPriceAmount','priceAmount',1],['maxPriceAmount','priceAmount',-1],['minAgeMonths','ageMonths',1],['maxAgeMonths','ageMonths',-1]])if(q[key])out=out.filter(p=>cmp*(p[field]-Number(q[key]))>=0);if(q.sort==='price_asc')out.sort((a,b)=>a.priceAmount-b.priceAmount);if(q.sort==='price_desc')out.sort((a,b)=>b.priceAmount-a.priceAmount);if(q.sort==='newest')out.reverse();return out}
api.use((req,res,next)=>{req.identity=tokens.get(req.headers.authorization?.replace('Bearer ',''));if(req.path.startsWith('/admin/')&&req.path!=='/admin/auth/login'&&req.identity?.role!=='admin')return fail(res,'请先登录店主管理后台',401);next()})
const buyerOnly=(req,res,next)=>req.identity?.role==='buyer'?next():fail(res,'请先登录买家账户',401)
// 本地模拟幂等重放，成功的相同提交返回原结果，不重复占用库存或产生订单。
api.use((req,res,next)=>{const key=req.headers['idempotency-key'];if(!key)return next();const fingerprint=req.method+req.path+JSON.stringify(req.body),owner=req.identity?.id||'guest',cacheKey=owner+key,old=replays.get(cacheKey);if(old)return old.fingerprint===fingerprint?res.status(old.status).json(old.body):fail(res,'幂等键与原提交内容不一致',409);const json=res.json.bind(res);res.json=body=>{if(res.statusCode<300)replays.set(cacheKey,{fingerprint,status:res.statusCode,body});return json(body)};next()})
api.get('/auth/captchas',(req,res)=>{const captchaId=id('captcha');captchas.add(captchaId);ok(res,{captchaId,imageBase64:'data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="120" height="44"><rect width="120" height="44" fill="#fff0dc"/><text x="16" y="30" font-size="26" fill="#ae4b20">DEMO</text></svg>').toString('base64'),expiresIn:300})})
api.post('/auth/sms-codes',(req,res)=>{const b=req.body;if(!/^1[3-9]\d{9}$/.test(b.phone)||!captchas.delete(b.captchaId)||b.captchaCode.toUpperCase()!=='DEMO')return fail(res,'手机号或图片验证码有误');const smsRequestId=id('sms');sms.set(smsRequestId,b.phone);ok(res,{smsRequestId,retryAfter:60})})
api.post('/auth/sms-login',(req,res)=>{const b=req.body;if(sms.get(b.smsRequestId)!==b.phone||b.smsCode!=='123456')return fail(res,'短信验证码错误');sms.delete(b.smsRequestId);let u=users.get(b.phone);if(!u){u={id:id('user'),phone:b.phone,nickname:'暖爪新朋友',avatarUrl:null,phoneMasked:mask(b.phone)};users.set(b.phone,u)}const accessToken=randomUUID();tokens.set(accessToken,{role:'buyer',id:u.id,user:u});ok(res,{accessToken,expiresIn:86400,user:{...u,phone:undefined}})})
api.post('/admin/auth/login',(req,res)=>{const b=req.body;if(b.username!=='admin'||b.password!=='WarmPaw2026'||!captchas.delete(b.captchaId)||b.captchaCode.toUpperCase()!=='DEMO')return fail(res,'账号、密码或图片验证码错误');const accessToken=randomUUID();tokens.set(accessToken,{role:'admin',id:'admin_1'});ok(res,{accessToken,expiresIn:86400,admin:{id:'admin_1',username:'admin',nickname:'暖爪店主'}})})
for(const path of ['/auth/logout','/admin/auth/logout'])api.post(path,(req,res)=>{tokens.delete(req.headers.authorization?.replace('Bearer ',''));ok(res,{})})
api.get('/me',buyerOnly,(req,res)=>ok(res,{...req.identity.user,phone:undefined}))
api.patch('/me',buyerOnly,(req,res)=>{if(!req.body.nickname?.trim())return fail(res,'昵称不能为空');req.identity.user.nickname=req.body.nickname.trim();ok(res,{...req.identity.user,phone:undefined})})
api.get('/home',(req,res)=>ok(res,{banners:shop.banners.filter(b=>b.enabled).map(b=>({...b,imageUrl:files.get(b.imageFileId)?.publicUrl||'/images/corgi.jpg'})),categories,recommendedPets:pets.filter(p=>p.isRecommended&&p.status==='on_sale').map(publicPet),latestPets:pets.filter(p=>p.status==='on_sale').map(publicPet),shop}))
api.get('/shop',(req,res)=>ok(res,shop));api.get('/pet-categories',(req,res)=>ok(res,categories))
api.get('/pets',(req,res)=>ok(res,page(filtered(pets.filter(p=>p.status!=='off'),req.query).map(publicPet),req.query)))
api.get('/pets/:id',(req,res)=>{const p=pets.find(p=>p.id===req.params.id&&p.status!=='off');return p?ok(res,publicPet(p)):fail(res,'宠物不存在或已下架',404)})
api.get('/agreements/current',(req,res)=>ok(res,agreement(req.query.type||'live_pet_trade')))
const labels={pending_paid:'待付款',paid:'待自提',completed:'已完成',cancelled:'已取消',refunding:'退款中',refunded:'已退款'}
function orderView(o){return {...o,userId:undefined,pickup:o.status==='paid'&&!o.afterSale?o.pickup:null,statusText:labels[o.status],availableActions:o.status==='pending_paid'?['pay','cancel']:o.status==='paid'?['view_pickup','confirm_health','apply_after_sale']:o.status==='completed'?['apply_after_sale']:[],afterSaleEligibility:{allowedTypes:o.afterSale?[]:o.status==='paid'?['refund_before_pickup']:o.status==='completed'?['health_issue']:[],allowedResolutions:o.afterSale?[]:o.status==='paid'?['full_refund']:o.status==='completed'?['full_refund','treatment_share']:[],blockedReason:o.afterSale?'已有售后申请':null},afterSaleStatus:o.afterSale?.status||'none'}}
function owned(req,res){const o=orders.find(o=>o.id===req.params.id&&(req.identity?.role==='admin'||o.userId===req.identity?.id));if(!o)fail(res,'订单不存在',404);return o}
api.post('/orders/preview',buyerOnly,(req,res)=>{const p=pets.find(p=>p.id===req.body.petId);if(!p)return fail(res,'宠物不存在',404);const a=agreement('live_pet_trade');ok(res,{product:publicPet(p),productVersion:p.version,amount:p.priceAmount,currency:'CNY',shop,agreementVersion:a.version,agreementContentHash:a.contentHash,paymentTimeoutMinutes:shop.paymentTimeoutMinutes,pickupRetentionHours:shop.pickupRetentionHours,healthGuaranteeDays:7,purchaseAllowed:p.status==='on_sale',blockedReason:p.status==='on_sale'?null:'宠物已被预订或售出'})})
api.post('/orders',buyerOnly,(req,res)=>{const b=req.body,p=pets.find(p=>p.id===b.petId),a=agreement('live_pet_trade');if(!p||p.status!=='on_sale'||p.version!==b.productVersion||p.priceAmount!==b.expectedAmount)return fail(res,'商品状态或价格已变更，请刷新',409);if(!b.agreementAccepted||b.agreementVersion!==a.version||b.agreementContentHash!==a.contentHash||b.contactPhone!==req.identity.user.phone||!b.contactName?.trim())return fail(res,'请核对本人手机号、姓名并同意协议');const o={id:id('order'),orderNo:'WP'+Date.now(),userId:req.identity.id,status:'pending_paid',product:{id:p.id,name:p.name,breed:p.breed,coverUrl:p.coverUrl},amount:p.priceAmount,refundedAmount:0,createdAt:now(),expiresAt:new Date(Date.now()+shop.paymentTimeoutMinutes*60000).toISOString(),paidAt:null,pickupDeadlineAt:null,completedAt:null,shopSnapshot:structuredClone(shop),contactName:b.contactName,contactPhoneMasked:mask(b.contactPhone),remark:b.remark||'',agreement:{...a,signedAt:now()},pickup:null,healthGuaranteeExpiresAt:null,afterSale:null,refunds:[]};orders.unshift(o);p.status='reserved';p.version++;p.activeOrderId=o.id;ok(res,orderView(o),201)})
api.get('/orders',buyerOnly,(req,res)=>{let list=orders.filter(o=>o.userId===req.identity.id);if(req.query.tab&&req.query.tab!=='all')list=list.filter(o=>req.query.tab==='after_sale'?o.afterSale:o.status===(req.query.tab==='pending_pickup'?'paid':req.query.tab));ok(res,page(list.map(orderView),req.query))})
api.get('/orders/:id',buyerOnly,(req,res)=>{const o=owned(req,res);if(o)ok(res,orderView(o))})
api.post('/orders/:id/cancel',buyerOnly,(req,res)=>{const o=owned(req,res);if(!o)return;if(o.status!=='pending_paid')return fail(res,'当前订单不可取消',409);o.status='cancelled';const p=pets.find(p=>p.id===o.product.id);p.status='on_sale';p.activeOrderId=null;p.version++;ok(res,orderView(o))})
api.post('/demo/orders/:id/pay',buyerOnly,(req,res)=>{const o=owned(req,res);if(!o)return;if(o.status!=='pending_paid')return fail(res,'订单不是待付款状态',409);o.status='paid';o.paidAt=now();o.pickupDeadlineAt=new Date(Date.now()+72*3600000).toISOString();o.pickup={code:randomUUID().slice(0,8).toUpperCase(),qrPayload:'demo:'+o.id,expiresAt:o.pickupDeadlineAt,buyerConfirmedAt:null};ok(res,orderView(o))})
api.get('/orders/:id/payment',buyerOnly,(req,res)=>{const o=owned(req,res);if(o)ok(res,{status:['paid','completed'].includes(o.status)?'succeeded':'pending',scene:'h5',orderStatus:o.status,nextPollAfter:2})})
api.get('/payment-capabilities',(req,res)=>ok(res,{methods:[{scene:'h5',enabled:false,disabledReason:'本地服务仅提供明确标识的演示支付'},{scene:'jsapi',enabled:false,disabledReason:'未配置微信商户'}]}))
api.post('/orders/:id/pickup-verification-codes',buyerOnly,(req,res)=>{const o=owned(req,res);if(!o)return;if(o.status!=='paid')return fail(res,'当前不可提货');const smsRequestId=id('pickup_sms');sms.set(smsRequestId,o.id);ok(res,{smsRequestId,retryAfter:60})})
api.post('/orders/:id/pickup-confirmations',buyerOnly,(req,res)=>{const o=owned(req,res);if(!o)return;const b=req.body;if(o.status!=='paid'||sms.get(b.smsRequestId)!==o.id||b.smsCode!=='123456'||!b.accepted||!['mentalState','eyesAndNose','coat','excretion'].every(k=>b.checks?.[k]===true))return fail(res,'请完成本人短信核验和全部健康确认');sms.delete(b.smsRequestId);o.pickup.buyerConfirmedAt=now();o.confirmationId=id('confirm');ok(res,{id:o.confirmationId,confirmedAt:o.pickup.buyerConfirmedAt})})
api.get('/admin/orders',(req,res)=>ok(res,page(filtered(orders,req.query).map(orderView),req.query)))
api.get('/admin/orders/:id',(req,res)=>{const o=owned(req,res);if(o)ok(res,orderView(o))})
api.post('/admin/pickups/lookup',(req,res)=>{const o=orders.find(o=>o.pickup?.code===req.body.pickupCode);if(!o)return fail(res,'自提码不存在',404);const allowed=o.status==='paid'&&Boolean(o.pickup.buyerConfirmedAt)&&!o.afterSale;ok(res,{order:orderView(o),contactName:o.contactName,contactPhoneMasked:o.contactPhoneMasked,buyerConfirmation:o.confirmationId?{id:o.confirmationId,confirmedAt:o.pickup.buyerConfirmedAt,validUntil:o.pickupDeadlineAt}:null,checksPassed:allowed,pickupAllowed:allowed,blockedReason:allowed?null:'需买家先完成健康确认，且订单必须待自提、无处理中售后'})})
api.post('/admin/orders/:id/pickup',(req,res)=>{const o=owned(req,res);if(!o)return;const b=req.body;if(o.status!=='paid'||!o.confirmationId||b.confirmationId!==o.confirmationId||b.pickupCode!==o.pickup.code||!b.quarantineVerified||o.afterSale)return fail(res,'核销条件未满足',409);o.status='completed';o.completedAt=now();o.healthGuaranteeExpiresAt=new Date(Date.now()+7*86400000).toISOString();const p=pets.find(p=>p.id===o.product.id);p.status='sold';p.version++;ok(res,orderView(o))})
// 诊断附件保留在内存中，通过角色和订单所有权控制访问。
const uploader=multer({storage:multer.memoryStorage(),limits:{fileSize:100*1024*1024}})
for(const path of ['/files','/admin/files'])api.post(path,(req,res,next)=>req.identity?next():fail(res,'请先登录',401),uploader.single('file'),(req,res)=>{if(!req.file)return fail(res,'请选择文件');if(req.file.size>(req.body.purpose==='pet_video'?100:10)*1024*1024)return fail(res,'文件超过当前用途的大小限制',413);if(req.identity.role==='buyer'&&(req.body.purpose!=='diagnosis'||!orders.some(o=>o.id===req.body.orderId&&o.userId===req.identity.id)))return fail(res,'附件必须属于本人订单',403);const fileId=id('file'),isPublic=['pet_image','pet_video','banner','quarantine_public'].includes(req.body.purpose);const file={id:fileId,originalName:req.file.originalname,mimeType:req.file.mimetype,sizeBytes:req.file.size,purpose:req.body.purpose,visibility:isPublic?'public':'private',status:'ready',publicUrl:isPublic?'/demo-files/'+fileId:null,createdAt:now(),owner:req.identity.id,buffer:req.file.buffer};files.set(fileId,file);ok(res,{...file,owner:undefined,buffer:undefined},201)})
app.get('/demo-files/:id',(req,res)=>{const f=files.get(req.params.id);if(!f?.buffer||f.visibility!=='public')return res.sendStatus(404);res.type(f.mimeType).send(f.buffer)})
api.get('/files/:id/access-url',(req,res)=>{const f=files.get(req.params.id);if(!f||!req.identity||(req.identity.role!=='admin'&&f.owner!==req.identity.id))return fail(res,'附件不存在',404);const ticket=randomUUID();tokens.set(ticket,{file:f.id});ok(res,{url:'/api/v1/demo-file-access/'+ticket,expiresIn:300})})
api.get('/demo-file-access/:ticket',(req,res)=>{const f=files.get(tokens.get(req.params.ticket)?.file);if(!f?.buffer)return res.sendStatus(404);res.type(f.mimeType).send(f.buffer)})
api.post('/orders/:id/after-sales',buyerOnly,(req,res)=>{const o=owned(req,res);if(!o)return;const b=req.body,eligibility=orderView(o).afterSaleEligibility;if(!eligibility.allowedTypes.includes(b.type)||!eligibility.allowedResolutions.includes(b.requestedResolution)||!b.reason?.trim())return fail(res,'当前订单不支持此售后方案',409);if(b.type==='health_issue'&&(!b.diagnosisFileIds?.length||b.diagnosisFileIds.some(i=>files.get(i)?.owner!==req.identity.id)))return fail(res,'请上传本人诊断报告');const s={id:id('sale'),orderId:o.id,version:1,status:'pending_review',...b,createdAt:now(),timeline:[{occurredAt:now(),label:'申请已提交',note:null}],approvedAmount:null};sales.unshift(s);o.afterSale=s;ok(res,s,201)})
api.get('/after-sales/:id',buyerOnly,(req,res)=>{const s=sales.find(s=>s.id===req.params.id&&orders.some(o=>o.id===s.orderId&&o.userId===req.identity.id));s?ok(res,s):fail(res,'售后不存在',404)})
const saleView=s=>({...s,order:orderView(orders.find(o=>o.id===s.orderId))})
api.get('/admin/after-sales',(req,res)=>ok(res,page(filtered(sales,req.query).map(saleView),req.query)))
api.get('/admin/after-sales/:id',(req,res)=>{const s=sales.find(s=>s.id===req.params.id);s?ok(res,saleView(s)):fail(res,'售后不存在',404)})
function refund(s,o,amount){o.refundedAmount+=amount;o.refunds.push({id:id('refund'),amount,status:'succeeded',failureReason:null});if(o.refundedAmount===o.amount)o.status='refunded';s.status='resolved';s.timeline.push({occurredAt:now(),label:'演示退款完成',note:'仅模拟状态变更，未发生真实资金退款'});const p=pets.find(p=>p.id===o.product.id);if(o.status==='refunded'){p.status='off';p.activeOrderId=null;p.version++}}
api.post('/admin/after-sales/:id/review',(req,res)=>{const s=sales.find(s=>s.id===req.params.id),b=req.body;if(!s||s.status!=='pending_review'||s.version!==b.version)return fail(res,'售后状态已改变',409);if(!b.reason?.trim())return fail(res,'请填写审核意见');s.reviewReason=b.reason;s.version++;s.timeline.push({occurredAt:now(),label:b.decision==='approve'?'店主已批准':'申请已驳回',note:b.reason});const o=orders.find(o=>o.id===s.orderId);if(b.decision==='reject')s.status='rejected';else if(s.requestedResolution==='treatment_share'){if(!(b.approvedAmount>0&&b.approvedAmount<=o.amount-o.refundedAmount))return fail(res,'退款金额超出范围');s.approvedAmount=b.approvedAmount;refund(s,o,b.approvedAmount)}else if(o.status==='paid')refund(s,o,o.amount-o.refundedAmount);else s.status='awaiting_return';ok(res,saleView(s))})
api.post('/admin/after-sales/:id/returns',(req,res)=>{const s=sales.find(s=>s.id===req.params.id);if(!s||s.status!=='awaiting_return'||s.version!==req.body.version||!req.body.received||!req.body.conditionNotes?.trim())return fail(res,'请核对退回状态与检查记录',409);s.version++;s.timeline.push({occurredAt:now(),label:'已到店退回',note:req.body.conditionNotes});const o=orders.find(o=>o.id===s.orderId);refund(s,o,o.amount-o.refundedAmount);ok(res,saleView(s))})
api.get('/admin/pets',(req,res)=>ok(res,page(filtered(pets,req.query).map(adminPet),req.query)))
api.get('/admin/pets/:id',(req,res)=>{const p=pets.find(p=>p.id===req.params.id);p?ok(res,adminPet(p)):fail(res,'宠物不存在',404)})
api.post('/admin/pets',(req,res)=>{const b=req.body;if(!b.name||!b.imageFileIds?.length||b.priceAmount<=0)return fail(res,'请填写名称、照片和价格');const p={...b,id:id('pet'),status:'off',version:1,currency:'CNY',coverUrl:files.get(b.imageFileIds[0])?.publicUrl,images:b.imageFileIds.map((i,n)=>({fileId:i,url:files.get(i)?.publicUrl,sortOrder:n})),activeOrderId:null,publishedAt:null};pets.unshift(p);ok(res,adminPet(p),201)})
api.put('/admin/pets/:id',(req,res)=>{const p=pets.find(p=>p.id===req.params.id);if(!p||p.version!==req.body.version||['sold','reserved'].includes(p.status))return fail(res,'档案版本已变更或已锁定',409);Object.assign(p,req.body,{version:p.version+1,coverUrl:files.get(req.body.imageFileIds[0])?.publicUrl,images:req.body.imageFileIds.map((i,n)=>({fileId:i,url:files.get(i)?.publicUrl,sortOrder:n}))});ok(res,adminPet(p))})
for(const action of ['publish','unpublish'])api.post('/admin/pets/:id/'+action,(req,res)=>{const p=pets.find(p=>p.id===req.params.id),b=req.body;if(!p||p.version!==b.version||p.status!==(action==='publish'?'off':'on_sale'))return fail(res,'状态已变化',409);if(action==='publish'&&(!b.healthyForSale||!b.quarantineVerified||!b.reviewNote||!p.quarantine?.publicImageFileIds?.length))return fail(res,'请上传公开检疫证明并完成人工核验');p.status=action==='publish'?'on_sale':'off';p.version++;p.publishedAt=now();ok(res,adminPet(p))})
api.get('/admin/shop',(req,res)=>ok(res,shop))
api.put('/admin/shop',(req,res)=>{if(req.body.version!==shop.version)return fail(res,'配置已更新，请重新加载',409);if(!req.body.name||req.body.banners?.some(b=>!b.title||!files.has(b.imageFileId)))return fail(res,'门店名称和轮播内容不完整');shop={...shop,...req.body,id:shop.id,version:shop.version+1};ok(res,shop)})
api.get('/admin/dashboard',(req,res)=>ok(res,{createdOrderCount:orders.length,paidOrderCount:orders.filter(o=>o.paidAt).length,grossSalesAmount:orders.filter(o=>o.paidAt).reduce((s,o)=>s+o.amount,0),onSalePetCount:pets.filter(p=>p.status==='on_sale').length,aiSessionCount:sessions.length,pendingTasks:{pickupCount:orders.filter(o=>o.status==='paid').length,afterSaleReviewCount:sales.filter(s=>s.status==='pending_review').length},updatedAt:now()}))
const knowledge=[{id:'kb_1',version:1,title:'幼犬到家第一周',category:'feeding',petType:'dog',format:'article',content:'保持原饮食，逐步适应新环境，定期咨询兽医。',question:null,answer:null,sourceName:'本地演示饲养手册',sourceUrl:null,breedNames:[],status:'published',indexStatus:'ready'}]
api.get('/admin/knowledge/entries',(req,res)=>ok(res,page(filtered(knowledge,req.query),req.query)))
api.post('/admin/knowledge/entries',(req,res)=>{const k={...req.body,id:id('kb'),version:1,indexStatus:'ready'};knowledge.unshift(k);ok(res,k,201)})
api.put('/admin/knowledge/entries/:id',(req,res)=>{const k=knowledge.find(k=>k.id===req.params.id);if(!k||k.version!==req.body.version)return fail(res,'知识版本已更新',409);Object.assign(k,req.body,{version:k.version+1,indexStatus:'ready'});ok(res,k)})
api.get('/admin/knowledge/import-template',(req,res)=>res.type('text/csv').send('\uFEFFtitle,category,petType,format,content,sourceName,status\n示例饲养知识,feeding,dog,article,请替换为审核后的真实正文,门店手册,draft\n'))
api.post('/admin/knowledge/index-rebuild-jobs',(req,res)=>{const j={id:id('job'),type:'index_rebuild',scope:req.body.scope,status:'succeeded',totalCount:knowledge.length,processedCount:knowledge.length,successCount:knowledge.length,failedCount:0};jobs.set(j.id,j);ok(res,j,202)})
api.post('/admin/knowledge/import-jobs',(req,res)=>{const file=files.get(req.body.fileId);if(!file)return fail(res,'导入文件不存在');/* 演示版不伪造解析成功，真实 Excel/CSV 导入交由后端实现。 */const j={id:id('job'),type:'import',scope:'knowledge',status:'failed',totalCount:0,processedCount:0,successCount:0,failedCount:0,errorMessage:'演示服务不执行文件导入，请通过新建知识录入；真实导入需接入后端。'};jobs.set(j.id,j);ok(res,j,202)})
api.get('/admin/knowledge/jobs/:id',(req,res)=>jobs.has(req.params.id)?ok(res,jobs.get(req.params.id)):fail(res,'任务不存在',404))
api.post('/guest-sessions',(req,res)=>{const guestToken=randomUUID();tokens.set(guestToken,{role:'guest',id:id('guest')});ok(res,{guestToken,expiresIn:86400})})
const aiOwner=req=>req.identity?.role==='buyer'?req.identity.id:tokens.get(req.headers['x-guest-token'])?.id
api.use('/ai',(req,res,next)=>aiOwner(req)?next():fail(res,'请重新创建会话',401))
api.post('/ai/sessions',(req,res)=>{const s={id:id('chat'),owner:aiOwner(req),title:'新会话',messages:[]};sessions.unshift(s);ok(res,{id:s.id,title:s.title},201)})
api.get('/ai/sessions',(req,res)=>ok(res,page(sessions.filter(s=>s.owner===aiOwner(req)).map(s=>({id:s.id,title:s.title})),req.query)))
function session(req,res){const s=sessions.find(s=>s.id===req.params.sid&&s.owner===aiOwner(req));if(!s)fail(res,'会话不存在',404);return s}
api.get('/ai/sessions/:sid/messages',(req,res)=>{const s=session(req,res);if(s)ok(res,{items:s.messages})})
api.get('/ai/sessions/:sid/messages/:mid',(req,res)=>{const s=session(req,res);if(s){const m=s.messages.find(m=>m.id===req.params.mid);m?ok(res,m):fail(res,'消息不存在',404)}})
api.put('/ai/sessions/:sid/messages/:mid/feedback',(req,res)=>{const s=session(req,res);if(s)ok(res,{messageId:req.params.mid,value:req.body.value,updatedAt:now()})})
api.post('/ai/sessions/:sid/messages',async(req,res)=>{const s=session(req,res);if(!s)return;const b=req.body;if(!b.content?.trim())return fail(res,'问题不能为空');let answer=s.messages.find(m=>m.role==='assistant'&&m.clientMessageId===b.clientMessageId);if(!answer){s.title=b.content.slice(0,20);s.messages.push({id:id('msg'),role:'user',content:b.content,status:'completed',clientMessageId:b.clientMessageId});const isOrder=/订单|自提/.test(b.content),signed=req.identity?.role==='buyer';answer={id:id('msg'),role:'assistant',clientMessageId:b.clientMessageId,status:'completed',content:isOrder?(signed?'以下是你本人的订单，请点击查看最新自提进度。':'订单信息需要本人登录后查询。'): '新朋友到家，先为它准备一个安静、安全的角落。第一周保持原有饮食，循序渐进地适应环境。\n\n请核对疫苗和驱虫记录；若出现持续呕吐、腹泻或精神不振，应及时联系兽医。以上为本地演示回复。',sources:isOrder?[]:[{title:'幼犬到家第一周',sourceName:'本地演示饲养手册',sourceUrl:null,excerpt:'保持原饮食，逐步适应环境。'}],productCards:[],orderCards:isOrder&&signed?orders.filter(o=>o.userId===req.identity.id).map(o=>({orderId:o.id,orderNo:o.orderNo,status:o.status,productName:o.product.name,nextAction:labels[o.status]})):[],actions:isOrder&&!signed?[{type:'login',label:'登录查看本人订单'}]:[],disclaimer:'演示内容，未调用 AI 模型；仅供参考'};s.messages.push(answer)}res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.flushHeaders();const send=(e,d)=>res.write(`event: ${e}\ndata: ${JSON.stringify(d)}\n\n`);send('meta',{assistantMessageId:answer.id});for(const text of answer.content.match(/.{1,12}|\n/g)||[]){if(res.destroyed)return;send('delta',{text});await new Promise(r=>setTimeout(r,35))}send('sources',{items:answer.sources});send('cards',{productCards:answer.productCards,orderCards:answer.orderCards});send('action',{items:answer.actions});send('done',{disclaimer:answer.disclaimer});res.end()})
api.use((req,res)=>fail(res,'该接口尚未在本地演示服务中实现',404))
app.use((error,req,res,next)=>{console.error(error.message);if(!res.headersSent)fail(res,error instanceof multer.MulterError?'上传文件过大':'演示请求处理失败',400)})
// Express 5 会把监听错误传给回调；只有成功绑定端口后才输出启动成功。
app.listen(8787, '127.0.0.1', error => {
  if (error) {
    console.error(error.code === 'EADDRINUSE'
      ? '演示服务启动失败：8787 端口已被占用。若本项目已启动，请直接访问 http://127.0.0.1:5173 和 http://127.0.0.1:5174，不要重复启动。'
      : `演示服务启动失败：${error.message}`)
    process.exitCode = 1
    return
  }
  console.log('暖爪演示 API http://127.0.0.1:8787 — 内存数据，重启重置，非生产服务')
})
