<script setup lang="ts">
import {ref,reactive,onMounted} from 'vue';import {useRoute,useRouter} from 'vue-router';import {buyer,date,upload,mutationKey} from '../../../shared/api';import type {Order,AfterSale} from '../../../shared/types';import {useLoad} from '../../../shared/useLoad';import LoadState from '../components/LoadState.vue'
const route=useRoute(),router=useRouter(),order=ref<Order>(),sale=ref<AfterSale>(),files=ref<{id:string;name:string}[]>([]),uploading=ref(false),form=reactive({type:'health_issue',requestedResolution:'full_refund',reason:'',diagnosisAt:'',amount:''}),key=mutationKey(),{loading,error,run}=useLoad()
const labels:Record<string,string>={pending_review:'等待店主审核',rejected:'申请已驳回',awaiting_return:'等待到店退回',refunding:'退款处理中',resolved:'处理已完成',awaiting_exchange:'等待换宠交付'}
const load=()=>run(async()=>{if(route.params.id)sale.value=await buyer('GET',`/after-sales/${route.params.id}`);else{order.value=await buyer('GET',`/orders/${route.params.orderId}`);form.type=order.value!.afterSaleEligibility.allowedTypes[0]||'';form.requestedResolution=order.value!.afterSaleEligibility.allowedResolutions[0]||''}})
async function attach(event:Event){const selected=(event.target as HTMLInputElement).files;if(!selected)return;uploading.value=true;await run(async()=>{for(const file of Array.from(selected).slice(0,5-files.value.length)){const result=await upload('buyer',file,'diagnosis',String(route.params.orderId));files.value.push({id:result.id,name:file.name})}});uploading.value=false}
async function submit(){await run(async()=>{const body={type:form.type,requestedResolution:form.requestedResolution,reason:form.reason,...(form.type==='health_issue'?{diagnosisAt:new Date(form.diagnosisAt).toISOString(),diagnosisFileIds:files.value.map(f=>f.id)}:{}),...(form.requestedResolution==='treatment_share'?{requestedAmount:Math.round(Number(form.amount)*100)}:{})};const path=`/orders/${route.params.orderId}/after-sales`;const result=await buyer<AfterSale>('POST',path,body,undefined,key(path,body));await router.replace(`/after-sales/${result.id}`)})}
onMounted(load)
</script>
<template><div class="container page narrow"><p class="eyebrow">WE ARE HERE FOR YOU</p><h1>{{sale?'让每一步，都有回应。':'让问题被认真对待。'}}</h1><LoadState v-if="!order&&!sale" :loading="loading" :error="error" @retry="load"/><section v-if="sale" class="panel stack"><span class="status orange">{{labels[sale.status]||sale.status}}</span><h2>售后申请 {{sale.id}}</h2><p>{{sale.reason}}</p><p v-if="sale.reviewReason">店主意见：{{sale.reviewReason}}</p><ol class="timeline"><li v-for="(item,index) in sale.timeline" :key="index"><strong>{{item.label}}</strong><small>{{date(item.occurredAt)}}</small><p>{{item.note}}</p></li></ol><div class="actions"><button class="btn secondary" :disabled="loading" @click="load">刷新进度</button><RouterLink class="btn" to="/shop">联系店主</RouterLink></div><p v-if="error" class="error-text">{{error}}</p></section><form v-else-if="order" class="panel stack" @submit.prevent="submit"><p v-if="order.afterSaleEligibility.blockedReason" class="notice">{{order.afterSaleEligibility.blockedReason}}</p><label>申请类型<select v-model="form.type"><option v-for="type in order.afterSaleEligibility.allowedTypes" :key="type" :value="type">{{type==='health_issue'?'健康问题申诉':'自提前退款'}}</option></select></label><label>期望处理方式<select v-model="form.requestedResolution"><option v-for="resolution in order.afterSaleEligibility.allowedResolutions" :key="resolution" :value="resolution">{{resolution==='full_refund'?'全额退款':resolution==='treatment_share'?'治疗费分担':'到店换宠'}}</option></select></label><label>问题说明<textarea v-model="form.reason" required maxlength="1000" rows="5" placeholder="请描述发现时间、情况与处理诉求"></textarea></label><template v-if="form.type==='health_issue'"><label>诊断时间<input v-model="form.diagnosisAt" type="datetime-local" required></label><label class="upload-box">上传诊断报告<input type="file" accept=".pdf,.jpg,.jpeg,.png" multiple :disabled="uploading||files.length>=5" @change="attach"><small>最多5份，每份不超过10MB。</small></label><ul class="file-list"><li v-for="(file,index) in files" :key="file.id">{{file.name}} <button type="button" class="text-link" @click="files.splice(index,1)">移除</button></li></ul></template><label v-if="form.requestedResolution==='treatment_share'">申请金额（元）<input v-model="form.amount" type="number" min="0.01" step="0.01" :max="(order.amount-order.refundedAmount)/100" required></label><p v-if="error" class="error-text" role="alert">{{error}}</p><button class="btn" :disabled="loading||uploading||!form.type||(form.type==='health_issue'&&!files.length)">{{loading?'正在提交…':'提交申请'}}</button></form></div></template>
