<script setup lang="ts">
import {ref,reactive,onMounted} from 'vue';import {useRoute,useRouter} from 'vue-router';import {buyer,money,mutationKey} from '../../../shared/api';import type {OrderPreview,Agreement,Order} from '../../../shared/types';import {useLoad} from '../../../shared/useLoad';import LoadState from '../components/LoadState.vue';import OrderSummary from '../components/OrderSummary.vue';import ShopCard from '../components/ShopCard.vue'
const route=useRoute(),router=useRouter(),preview=ref<OrderPreview>(),agreement=ref<Agreement>(),accepted=ref(false),open=ref(false),form=reactive({contactName:'',contactPhone:'',remark:'',visitAt:''}),key=mutationKey(),{loading,error,run}=useLoad()
// 输入按北京时间解释，避免用户设备时区改变预约时刻。
const localDate=(value:Date)=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(value).replace(' ','T')
const minVisit=localDate(new Date()),maxVisit=localDate(new Date(Date.now()+7*86400000))
const load=()=>run(async()=>{const [p,a]=await Promise.all([buyer<OrderPreview>('POST','/orders/preview',{petId:route.params.petId}),buyer<Agreement>('GET','/agreements/current',undefined,{type:'live_pet_trade'})]);preview.value=p;agreement.value=a;accepted.value=false;if(p.agreementContentHash!==a.contentHash)throw new Error('协议已更新，请刷新后重新阅读')})
async function submit(){if(!preview.value||!agreement.value)return;await run(async()=>{const p=preview.value!;const body={petId:route.params.petId,productVersion:p.productVersion,expectedAmount:p.amount,...form,visitAt:form.visitAt+':00+08:00',agreementVersion:p.agreementVersion,agreementContentHash:p.agreementContentHash,agreementAccepted:accepted.value};const path='/orders';const order=await buyer<Order>('POST',path,body,undefined,key(path,body));await router.push(`/orders/${order.id}`)})}
onMounted(load)
</script>
<template><div class="container page"><p class="eyebrow">ONE STEP CLOSER</p><h1>预约这一次相遇</h1><p class="lead">提交预约 — 店长确认 — 到店付款并接宠</p><LoadState v-if="!preview" :loading="loading" :error="error" @retry="load"/><form v-if="preview" class="checkout-grid" @submit.prevent="submit"><div class="stack"><OrderSummary :product="preview.product" :amount="preview.amount"/><ShopCard :shop="preview.shop"/><div class="panel stack"><label>联系人<input v-model="form.contactName" required maxlength="30" autocomplete="name" placeholder="请填写本人姓名"></label><label>已验证手机号<input v-model="form.contactPhone" required type="tel" pattern="1[3-9][0-9]{9}" maxlength="11" placeholder="请填写本次登录的手机号"><small>仅支持本人到店自提，须与登录手机号一致。</small></label><label>到店时间（北京时间）<input v-model="form.visitAt" type="datetime-local" :min="minVisit" :max="maxVisit" required><small>可预约未来7天，营业时间：{{preview.shop.businessHours}}</small></label><label>预约备注（选填）<textarea v-model="form.remark" maxlength="500" placeholder="例如：计划周日下午到店"></textarea></label></div></div><aside class="panel order-total"><h2>到店付款金额</h2><div class="between"><span>{{preview.product.name}} · {{preview.product.breed}}</span><strong>{{money(preview.amount)}}</strong></div><p class="muted">数量 1 · 无配送费用</p><hr><p>到店支付 · 线上不扣款</p><strong class="price large">{{money(preview.amount)}}</strong><button type="button" class="btn secondary full" @click="open=true">阅读《活体宠物交易须知》</button><label class="check"><input type="checkbox" v-model="accepted" required>我已阅读并同意交易须知</label><p v-if="!preview.purchaseAllowed" class="error-text">{{preview.blockedReason}}</p><p v-if="error" class="error-text" role="alert">{{error}} <button type="button" class="text-link" @click="load">刷新结算信息</button></p><button class="btn full" :disabled="loading||!accepted||!preview.purchaseAllowed">{{loading?'正在提交…':'提交到店预约'}}</button><small class="muted">提交后占用此宠物；店长须在24小时内且不晚于到店时间确认。确认后保留至约定时间后2小时。每个账号限1个有效预约。</small></aside></form><div v-if="open" class="modal-layer" @click.self="open=false" @keydown.esc="open=false"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="agreement-title"><div class="section-heading"><h2 id="agreement-title">{{agreement?.title}}</h2><button class="icon-button" aria-label="关闭协议" @click="open=false">×</button></div><article class="agreement-text">{{agreement?.content}}</article><button class="btn" @click="accepted=true;open=false">已阅读并同意</button></section></div></div></template>
