<script setup lang="ts">
import { ref,onMounted,onUnmounted } from 'vue'
import {buyer} from '../../../shared/api'
import {useLoad} from '../../../shared/useLoad'
import type {HomeData} from '../../../shared/types'
import PetCard from '../components/PetCard.vue';import ShopCard from '../components/ShopCard.vue';import LoadState from '../components/LoadState.vue'
const data=ref<HomeData>(),slide=ref(0),paused=ref(false),{loading,error,run}=useLoad();let timer:ReturnType<typeof setInterval>
const load=()=>run(async()=>{data.value=await buyer<HomeData>('GET','/home')})
onMounted(()=>{void load();timer=setInterval(()=>{if(!paused.value&&!document.hidden&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&data.value?.banners.length)slide.value=(slide.value+1)%data.value.banners.length},5000)})
onUnmounted(()=>clearInterval(timer))
</script>
<template><div class="container"><LoadState :loading="loading" :error="error" @retry="load"/><template v-if="data"><section class="hero"><div class="hero-copy"><p class="eyebrow">A LITTLE PAW. A LOT OF LOVE.</p><h1>一个小小的相遇，<br>让日常多一点温柔。</h1><p class="lead">发现与你合拍的猫咪与狗狗。<br>看见真实档案，在门店安心相遇。</p><div class="actions"><RouterLink class="btn" to="/pets">去认识它们 →</RouterLink><RouterLink class="btn secondary" to="/ai">问问 AI 怎么养</RouterLink></div><p class="hero-trust">一宠一档 / 检疫证明可查 / 到店当面核验</p></div><div v-if="data.banners.length" class="hero-media" @mouseenter="paused=true" @mouseleave="paused=false" @focusin="paused=true" @focusout="paused=false"><Transition name="photo" mode="out-in"><img :key="slide" :src="data.banners[slide]?.imageUrl" :alt="data.banners[slide]?.title" width="580" height="510"></Transition><div class="hero-caption"><strong>{{data.banners[slide]?.title}}</strong><RouterLink v-if="data.banners[slide]?.linkType==='pet'" :to="`/pets/${data.banners[slide]?.petId}`" class="btn secondary">认识我 →</RouterLink><p v-else>{{data.banners[slide]?.noticeText}}</p></div><div class="carousel-controls"><button v-for="(banner,index) in data.banners" :key="banner.id" :class="{active:index===slide}" :aria-label="`查看第 ${index+1} 张照片`" :aria-pressed="index===slide" @click="slide=index"></button><button class="carousel-pause" @click="paused=!paused">{{paused?'播放轮播':'暂停轮播'}}</button></div></div></section><section class="home-pets"><div class="actions" style="margin-bottom:32px"><RouterLink v-for="category in data.categories" :key="category.code" :to="`/pets?category=${category.code}`" class="btn secondary">认识{{category.name}} →</RouterLink></div><div class="section-heading"><div><p class="eyebrow">MEET YOUR COMPANION</p><h2>每一只，都值得认真认识。</h2></div><RouterLink to="/pets" class="text-link">查看全部 →</RouterLink></div><div class="pet-grid"><PetCard v-for="pet in data.recommendedPets.slice(0,4)" :key="pet.id" :pet="pet"/></div></section><section v-if="data.latestPets.length" class="home-pets"><div class="section-heading"><div><p class="eyebrow">NEW LITTLE FRIENDS</p><h2>新来的小伙伴</h2></div><RouterLink to="/pets" class="text-link">发现更多 →</RouterLink></div><div class="pet-grid"><PetCard v-for="pet in data.latestPets.slice(0,4)" :key="pet.id" :pet="pet"/></div></section><ShopCard :shop="data.shop"/></template></div></template>
