<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue';import {useRoute,useRouter} from 'vue-router';import {buyer,saveAuth,isDemo,isJavaLocal} from '../../../shared/api';import type {LoginResult} from '../../../shared/types';import {useLoad} from '../../../shared/useLoad'
const route=useRoute(),router=useRouter(),phone=ref(''),smsCode=ref(''),captchaCode=ref(''),captcha=ref<{captchaId:string;imageBase64:string}>(),smsRequestId=ref(''),count=ref(0),bindTicket=ref(''),{loading,error,run}=useLoad();let timer:ReturnType<typeof setInterval>
const validPath=(value:unknown)=>typeof value==='string'&&value.startsWith('/')&&!value.startsWith('//')?value:'/'
const destination=()=>validPath(route.query.redirect||sessionStorage.getItem('warmpaw:return'))
async function refreshCaptcha(){captcha.value=await buyer('GET','/auth/captchas',undefined,{purpose:'sms'});captchaCode.value=''}
async function sendCode(){if(!/^1[3-9]\d{9}$/.test(phone.value)){error.value='请输入正确的手机号';return}await run(async()=>{const result=await buyer<{smsRequestId:string;retryAfter:number}>('POST','/auth/sms-codes',{phone:phone.value,purpose:bindTicket.value?'wechat_bind':'login',captchaId:captcha.value?.captchaId,captchaCode:captchaCode.value,...(bindTicket.value?{bindTicket:bindTicket.value}:{})});smsRequestId.value=result.smsRequestId;count.value=result.retryAfter});if(error.value)await refreshCaptcha()}
async function login(){await run(async()=>{const body={phone:phone.value,smsRequestId:smsRequestId.value,smsCode:smsCode.value};const result=await buyer<LoginResult>('POST',bindTicket.value?'/auth/wechat/bind-phone':'/auth/sms-login',bindTicket.value?{...body,bindTicket:bindTicket.value}:body);saveAuth('buyer',result);const target=destination();sessionStorage.removeItem('warmpaw:return');await router.replace(target)})}
async function wechat(){await run(async()=>{sessionStorage.setItem('warmpaw:return',destination());const result=await buyer<{authorizeUrl:string}>('GET','/auth/wechat/authorize-url',undefined,{scene:'login',returnPath:destination()});const url=new URL(result.authorizeUrl);if(url.protocol!=='https:'||url.hostname!=='open.weixin.qq.com')throw new Error('微信授权地址无效');location.assign(url.href)})}
onMounted(()=>{timer=setInterval(()=>{if(count.value>0)count.value--},1000);void run(async()=>{await refreshCaptcha();if(route.query.code&&route.query.state){const body={code:String(route.query.code),state:String(route.query.state)};await router.replace('/login');const result=await buyer<{status:string;login?:LoginResult;bindTicket?:string}>('POST','/auth/wechat/login',body);if(result.login){saveAuth('buyer',result.login);await router.replace(destination())}else if(result.status==='wechat_ready')await router.replace(destination());else bindTicket.value=result.bindTicket||''}})})
onUnmounted(()=>clearInterval(timer))
</script>
<template><div class="container page login-layout"><img class="login-photo" src="/images/cat.jpg" alt="安静陪伴的猫咪"><form class="login-form panel" @submit.prevent="login"><p class="eyebrow">WELCOME HOME</p><h1>{{bindTicket?'绑定你的手机号':'你好，未来的家人。'}}</h1><p class="muted">登录后可下单、查看订单和自提凭证。</p><p v-if="isJavaLocal" class="notice">本地联调：请填写图片中的随机验证码；短信验证码保存在本机开发收件箱，不会发送真实短信。</p><p v-else-if="isDemo" class="notice">演示登录：任意有效手机号，图片码 DEMO，短信码 123456。不会发送真实短信。</p><label>手机号<input v-model="phone" type="tel" autocomplete="tel" pattern="1[3-9][0-9]{9}" required maxlength="11" placeholder="请输入手机号"></label><label>图片验证码<div class="captcha-row"><input v-model="captchaCode" maxlength="6" placeholder="图中文字"><button type="button" class="captcha" aria-label="刷新图片验证码" @click="run(refreshCaptcha)"><img v-if="captcha" :src="captcha.imageBase64" alt="图片验证码，点击刷新"></button></div></label><label>短信验证码<div class="captcha-row"><input v-model="smsCode" inputmode="numeric" pattern="[0-9]{6}" required maxlength="6" placeholder="输入6位验证码"><button type="button" class="btn secondary" :disabled="loading||count>0||!captchaCode" @click="sendCode">{{count?`${count}秒后重发`:'获取验证码'}}</button></div></label><p v-if="error" class="error-text" role="alert">{{error}}</p><button class="btn full" :disabled="loading||!smsRequestId">{{loading?'请稍候…':'登录并继续'}}</button><button v-if="!isDemo&&!bindTicket" type="button" class="btn secondary full" :disabled="loading" @click="wechat">微信授权快捷登录</button><p class="small muted">手机号仅用于本人身份核验与门店交付联系。</p></form></div></template>
