<script setup lang="ts">
import QrCode from '../components/QrCode.vue'
import {ref,onMounted,onUnmounted} from 'vue';import {useRoute,useRouter} from 'vue-router';import {buyer,isDemo,date,mutationKey,ApiError} from '../../../shared/api';import type {Order,Payment} from '../../../shared/types';import {useLoad} from '../../../shared/useLoad';import OrderSummary from '../components/OrderSummary.vue';import LoadState from '../components/LoadState.vue'
declare global {interface Window {WeixinJSBridge?: {invoke:(method:string,params:Record<string,string>,callback:(result:{err_msg:string})=>void)=>void}}}
const route=useRoute(),router=useRouter(),order=ref<Order>(),message=ref(''),copied=ref(false),key=mutationKey(),{loading,error,run}=useLoad();let timeout:ReturnType<typeof setTimeout>|undefined;let stopped=false
const path=`/orders/${route.params.orderId}`,resumeUrl=location.origin+path+'/payment',desktop=!/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent)
async function load(){await run(async()=>{order.value=await buyer('GET',path)})}
async function check(attempt=0){if(stopped)return;try{const result=await buyer<Payment>('GET',path+'/payment');if(stopped)return;if(result.status==='succeeded'){await router.replace(path+'/pickup');return}order.value=await buyer('GET',path);if(result.status==='pending'&&attempt<14)timeout=setTimeout(()=>void check(attempt+1),Math.max(result.nextPollAfter||2,2)*1000);else message.value='尚未确认支付成功。请查看订单状态，或稍后刷新。'}catch(e){error.value=e instanceof Error?e.message:'查询失败'}}
async function pay(){await run(async()=>{if(isDemo){await buyer('POST',`/demo/orders/${route.params.orderId}/pay`,{},undefined,key(path+'/demo-pay',{}));await check();return}const scene=/MicroMessenger/i.test(navigator.userAgent)?'jsapi':'h5';const caps=await buyer<{methods:{scene:string;enabled:boolean;disabledReason:string|null}[]}>('GET','/payment-capabilities');const method=caps.methods.find(m=>m.scene===scene);if(!method?.enabled)throw new Error(method?.disabledReason||'当前支付方式暂不可用，请联系店主');const body={scene,returnPath:path+'/payment'};let result:Payment;try{result=await buyer<Payment>('POST',path+'/payments',body,undefined,key(path+'/payments',body))}catch(e){if(e instanceof ApiError&&e.code==='WECHAT_AUTH_REQUIRED'){sessionStorage.setItem('warmpaw:return',path+'/payment');const url=await buyer<{authorizeUrl:string}>('GET','/auth/wechat/authorize-url',undefined,{scene:'pay',returnPath:path+'/payment'});const parsed=new URL(url.authorizeUrl);if(parsed.protocol!=='https:'||parsed.hostname!=='open.weixin.qq.com')throw new Error('微信授权地址无效');location.assign(parsed.href);return}throw e}if(result.status!=='pending'){await check();return}if(result.scene==='h5'&&result.h5Url){const url=new URL(result.h5Url);if(url.protocol!=='https:'||!(url.hostname==='wx.tenpay.com'||url.hostname.endsWith('.tenpay.com')))throw new Error('支付地址无效，请联系店主');location.assign(url.href)}else if(result.invokeParams){if(!window.WeixinJSBridge)throw new Error('请在微信中打开当前订单');window.WeixinJSBridge.invoke('getBrandWCPayRequest',result.invokeParams,()=>void check())}})}
async function copy(){try{await navigator.clipboard.writeText(resumeUrl);copied.value=true}catch{error.value='无法自动复制，请手动选择下方链接'}}
onMounted(async()=>{await load();if(order.value?.status==='paid')await router.replace(path+'/pickup');else if(order.value?.status!=='pending_paid')message.value='请返回订单查看最新状态。';else if(!isDemo)void check()});onUnmounted(()=>{stopped=true;clearTimeout(timeout)})
</script>
<template><div class="container page narrow"><p class="eyebrow">ONE STEP CLOSER</p><h1>{{desktop&&!isDemo?'在手机上继续付款':'完成这一次相遇'}}</h1><LoadState v-if="!order" :loading="loading" :error="error" @retry="load"/><template v-if="order"><OrderSummary :product="order.product" :amount="order.amount"/><div class="panel stack"><p>订单 {{order.orderNo}}</p><p>付款截止：{{date(order.expiresAt)}}</p><p v-if="isDemo" class="notice">这是演示订单。下面的操作只更新本地演示数据，不会调用微信或扣款。</p><template v-if="desktop&&!isDemo"><p>请在手机上打开此链接，登录本人账号后继续支付。</p><QrCode :value="resumeUrl" label="扫码在手机继续付款"/><input :value="resumeUrl" aria-label="手机继续付款链接" readonly><button class="btn" @click="copy">{{copied?'链接已复制':'复制订单链接'}}</button></template><button v-else-if="order.status==='pending_paid'" class="btn full" :disabled="loading" @click="pay">{{loading?'正在处理…':isDemo?'模拟支付成功（无扣款）':'微信支付'}}</button><p v-if="message" role="status">{{message}}</p><p v-if="error" class="error-text" role="alert">{{error}}</p><div class="actions"><button class="btn secondary" @click="check()">刷新支付结果</button><RouterLink class="text-link" :to="path">返回订单</RouterLink></div></div></template></div></template>
