<script setup lang="ts">
import {ref,reactive,onMounted,watch} from 'vue';import {useRoute,useRouter} from 'vue-router'
import {buyer} from '../../../shared/api';import type {Pet,Page,Category} from '../../../shared/types';import {useLoad} from '../../../shared/useLoad'
import PetCard from '../components/PetCard.vue';import LoadState from '../components/LoadState.vue'
const route=useRoute(),router=useRouter(),{loading,error,run}=useLoad(),result=ref<Page<Pet>>(),categories=ref<Category[]>([]),drawer=ref(false)
const form=reactive({keyword:String(route.query.keyword||''),category:String(route.query.category||''),breed:'',min:'',max:'',gender:'',minAge:'',maxAge:'',color:'',sort:'comprehensive'});const validation=ref('')
async function load(page=1){validation.value='';if(form.min&&form.max&&Number(form.min)>Number(form.max)){validation.value='最低价格不能高于最高价格';return}if(form.minAge&&form.maxAge&&Number(form.minAge)>Number(form.maxAge)){validation.value='最小月龄不能大于最大月龄';return}await run(async()=>{const params:Record<string,unknown>={page,pageSize:12};for(const key of ['keyword','category','breed','gender','color','sort'] as const)if(form[key])params[key]=form[key];if(form.min)params.minPriceAmount=Math.round(Number(form.min)*100);if(form.max)params.maxPriceAmount=Math.round(Number(form.max)*100);if(form.minAge)params.minAgeMonths=Number(form.minAge);if(form.maxAge)params.maxAgeMonths=Number(form.maxAge);result.value=await buyer<Page<Pet>>('GET','/pets',undefined,params);await router.replace({query:{...(form.category?{category:form.category}:{}),...(form.keyword?{keyword:form.keyword}:{})}});if(!error.value)drawer.value=false})}
function reset(){Object.assign(form,{keyword:'',category:'',breed:'',min:'',max:'',gender:'',minAge:'',maxAge:'',color:'',sort:'comprehensive'});void load()}
watch(()=>form.category,()=>{form.breed='';void load()})
onMounted(async()=>{void load();try{categories.value=await buyer<Category[]>('GET','/pet-categories')}catch{/* 商品列表仍可独立使用。 */}})
</script>
<template><div class="container page"><p class="eyebrow">FIND YOUR LITTLE FRIEND</p><h1>寻找与你合拍的它</h1><p class="lead">品种、性格、年龄慢慢挑；每只宠物都有独立档案。</p><form class="search-row" @submit.prevent="load()"><input v-model="form.keyword" aria-label="搜索宠物" placeholder="搜索品种、毛色、性格或名字…" maxlength="50"><button class="btn">搜索</button></form><div class="filter-bar"><div class="tabs"><button v-for="item in [['','全部'],['cat','猫咪'],['dog','狗狗']]" :key="item[0]" :class="{active:form.category===item[0]}" @click="form.category=item[0]">{{item[1]}}</button></div><button class="btn secondary" @click="drawer=true">品种与价格筛选</button><select v-model="form.sort" aria-label="排序" @change="load()"><option value="comprehensive">综合推荐</option><option value="newest">最新上架</option><option value="price_asc">价格从低到高</option><option value="price_desc">价格从高到低</option></select></div><LoadState :loading="loading" :error="error" @retry="load()"/><template v-if="result&&!loading"><p class="muted">找到 {{result.total}} 位小伙伴</p><div v-if="result.items.length" class="pet-grid"><PetCard v-for="pet in result.items" :key="pet.id" :pet="pet"/></div><div v-else class="empty"><h2>试试放宽一点条件。</h2><p>暂时没有符合条件的小伙伴。</p><button class="btn" @click="reset">清除筛选条件</button></div><div v-if="result.total>12" class="pagination"><button :disabled="result.page===1" class="btn secondary" @click="load(result.page-1)">上一页</button><span>第 {{result.page}} 页</span><button :disabled="result.page*12>=result.total" class="btn secondary" @click="load(result.page+1)">下一页</button></div></template><Transition name="drawer"><div v-if="drawer" class="modal-layer" @click.self="drawer=false" @keydown.esc="drawer=false"><section class="drawer" role="dialog" aria-modal="true" aria-labelledby="filter-title"><div class="section-heading"><h2 id="filter-title">找到合适的小伙伴</h2><button class="icon-button" aria-label="关闭筛选" @click="drawer=false">×</button></div><label>品种<select v-model="form.breed"><option value="">全部品种</option><option v-for="breed in categories.filter(c=>!form.category||c.code===form.category).flatMap(c=>c.breeds)" :key="breed">{{breed}}</option></select></label><div class="form-grid"><label>最低价格（元）<input v-model="form.min" type="number" min="0"></label><label>最高价格（元）<input v-model="form.max" type="number" min="0"></label><label>最小月龄<input v-model="form.minAge" type="number" min="0" max="360"></label><label>最大月龄<input v-model="form.maxAge" type="number" min="0" max="360"></label></div><label>性别<select v-model="form.gender"><option value="">不限</option><option value="male">弟弟</option><option value="female">妹妹</option></select></label><label>毛色<input v-model="form.color" maxlength="30"></label><p v-if="validation" role="alert" class="error-text">{{validation}}</p><div class="actions"><button class="btn secondary" @click="reset">重置</button><button class="btn" @click="load()">查看筛选结果</button></div></section></div></Transition></div></template>
