<script setup lang="ts">
import QrCode from '../components/QrCode.vue'
import {ref,reactive,onMounted,onUnmounted} from 'vue';import {useRoute} from 'vue-router';import {buyer,isDemo,date,mutationKey} from '../../../shared/api';import type {Order,Agreement} from '../../../shared/types';import {useLoad} from '../../../shared/useLoad';import LoadState from '../components/LoadState.vue';import OrderSummary from '../components/OrderSummary.vue'
const route=useRoute(),order=ref<Order>(),agreement=ref<Agreement>(),smsRequestId=ref(''),smsCode=ref(''),accepted=ref(false),count=ref(0),checks=reactive({mentalState:false,eyesAndNose:false,coat:false,excretion:false}),key=mutationKey(),{loading,error,run}=useLoad();const path=`/orders/${route.params.orderId}`;let timer:ReturnType<typeof setInterval>
const labels={mentalState:'精神状态',eyesAndNose:'眼鼻情况',coat:'毛发与皮肤',excretion:'排泄物情况'}
const load=()=>run(async()=>{order.value=await buyer('GET',path);agreement.value=await buyer('GET','/agreements/current',undefined,{type:'pickup_confirmation'})})
const send=()=>run(async()=>{const data=await buyer<{smsRequestId:string;retryAfter:number}>('POST',path+'/pickup-verification-codes');smsRequestId.value=data.smsRequestId;count.value=data.retryAfter})
const confirm=()=>run(async()=>{const body={smsRequestId:smsRequestId.value,smsCode:smsCode.value,confirmationVersion:agreement.value?.version,confirmationContentHash:agreement.value?.contentHash,accepted:accepted.value,checks};await buyer('POST',path+'/pickup-confirmations',body,undefined,key(path+'/pickup-confirmations',body));order.value=await buyer('GET',path)})
onMounted(()=>{void load();timer=setInterval(()=>{if(count.value>0)count.value--},1000)});onUnmounted(()=>clearInterval(timer))
</script>
<template><div class="container page narrow"><div class="section-heading"><h1>期待与你见面。</h1><button class="btn secondary" :disabled="loading" @click="load">刷新状态</button></div><LoadState v-if="!order" :loading="loading" :error="error" @retry="load"/><template v-if="order"><OrderSummary :product="order.product" :amount="order.amount"/><section v-if="order.pickup&&order.status==='paid'" class="panel pickup-code"><span class="status">{{order.statusText}}</span><h2>你的自提码</h2><QrCode :value="order.pickup.qrPayload" label="自提凭证二维码"/><strong>{{order.pickup.code}}</strong><p>仅向店主出示，请勿转发。</p><p class="muted">请在 {{date(order.pickupDeadlineAt)}} 前到店</p></section><section v-if="order.availableActions.includes('confirm_health')&&!order.pickup?.buyerConfirmedAt" class="panel stack"><h2>到店健康确认</h2><p>请现场逐项观察。如有疑问，先与店主沟通。</p><label v-for="(label,key) in labels" :key="key" class="check"><input v-model="checks[key]" type="checkbox">{{label}}已现场核验</label><article class="agreement-text">{{agreement?.content}}</article><label class="check"><input v-model="accepted" type="checkbox">我已阅读并同意上述现场确认内容</label><p v-if="isDemo" class="notice">演示验证码 123456，不会发送真实短信。</p><label>本人短信验证码<div class="captcha-row"><input v-model="smsCode" inputmode="numeric" maxlength="6" placeholder="输入6位验证码"><button class="btn secondary" :disabled="loading||count>0" @click="send">{{count?`${count}秒后重发`:'获取验证码'}}</button></div></label><button class="btn" :disabled="loading||!Object.values(checks).every(Boolean)||!accepted||!smsRequestId||smsCode.length!==6" @click="confirm">确认健康，提交核验</button></section><section v-else class="panel"><h2>{{order.status==='completed'?'交付已完成':order.pickup?.buyerConfirmedAt?'请交给店主完成最后一步':'当前暂不可核验'}}</h2><p>{{order.status==='completed'?'欢迎小伙伴成为你的家人。':order.pickup?.buyerConfirmedAt?'本人确认已提交，仍需店主办理交付核销。':'请查看订单状态或联系店主。'}}</p></section><p v-if="error" class="error-text" role="alert">{{error}}</p><RouterLink :to="path" class="text-link">返回订单详情 →</RouterLink></template></div></template>
