<script setup lang="ts">
import {ref,reactive,onMounted,onUnmounted} from 'vue';import {admin} from '../../../shared/api';import type {Page} from '../../../shared/types';import type {Knowledge} from '../../../shared/adminTypes';import {useLoad} from '../../../shared/useLoad';import {ElMessage} from 'element-plus'
const result=ref<Page<Knowledge>>(),keyword=ref(''),status=ref(''),edit=ref(false),selected=ref<Knowledge>(),reviewed=ref(false),pageNumber=ref(1),{loading,error,run}=useLoad();let timer:ReturnType<typeof setTimeout>|undefined,disposed=false
const form=reactive({title:'',category:'feeding',petType:'dog',format:'article' as 'article'|'qa',content:'',question:'',answer:'',sourceName:'',sourceUrl:'',status:'draft',breedNames:[] as string[]})
const labels:Record<string,string>={not_indexed:'未发布',pending:'等待更新',indexing:'更新中',ready:'可用于回答',failed:'更新失败'}
// 自动刷新发布结果，保存成功与“可用于回答”分开显示；离开页面后停止轮询。
async function refresh(){const data=await admin<Page<Knowledge>>('GET','/admin/knowledge/entries',undefined,{keyword:keyword.value,page:pageNumber.value,pageSize:20,...(status.value?{status:status.value}:{})});if(disposed)return;result.value=data;clearTimeout(timer);if(data.items.some(k=>['pending','indexing'].includes(k.indexStatus)))timer=setTimeout(()=>{void refresh().catch(e=>{error.value=e instanceof Error?e.message:'更新状态查询失败'})},2000)}
const load=()=>run(refresh)
function search(){pageNumber.value=1;void load()}
function open(row?:Knowledge){selected.value=row;reviewed.value=false;error.value='';Object.assign(form,row?{title:row.title,category:row.category,petType:row.petType,format:row.format,content:row.content||'',question:row.question||'',answer:row.answer||'',sourceName:row.sourceName,sourceUrl:row.sourceUrl||'',status:row.status,breedNames:[...row.breedNames]}:{title:'',category:'feeding',petType:'dog',format:'article',content:'',question:'',answer:'',sourceName:'',sourceUrl:'',status:'draft',breedNames:[]});edit.value=true}
const save=()=>run(async()=>{if(!form.title.trim()||!form.sourceName.trim()||(form.format==='article'?!form.content.trim():!form.question.trim()||!form.answer.trim()))throw new Error('请填写标题、内容和来源');if(form.status==='published'&&!reviewed.value)throw new Error('请先审核并确认知识内容与来源');const body={title:form.title,category:form.category,petType:form.petType,format:form.format,sourceName:form.sourceName,sourceUrl:form.sourceUrl||null,status:form.status,breedNames:form.breedNames,...(form.format==='article'?{content:form.content}:{question:form.question,answer:form.answer}),...(selected.value?{version:selected.value.version}:{})};await admin(selected.value?'PUT':'POST',selected.value?`/admin/knowledge/entries/${selected.value.id}`:'/admin/knowledge/entries',body);ElMessage.success(form.status==='published'?'审核已提交，更新完成后可用于回答':form.status==='archived'?'已归档，不再用于新的回答':'草稿已保存');edit.value=false;await refresh()})
onMounted(load);onUnmounted(()=>{disposed=true;clearTimeout(timer)})
</script>
<template>
 <div class="section-title"><div><p class="eyebrow">KNOWLEDGE LIBRARY</p><h2>让每次回答，有据可依。</h2></div><el-button type="primary" size="large" :disabled="loading" @click="open()">＋ 新建知识</el-button></div>
 <p class="muted">先保存草稿，核对内容与来源后发布。只有标记为“可用于回答”的已发布知识会被助手引用；归档后立即停止用于新的检索。</p>
 <div class="toolbar"><el-input v-model="keyword" placeholder="搜索知识标题或内容" aria-label="搜索知识" @keyup.enter="search"/><el-select v-model="status" placeholder="全部状态" clearable aria-label="筛选发布状态" style="width:160px" @change="search"><el-option value="draft" label="草稿"/><el-option value="published" label="已发布"/><el-option value="archived" label="已归档"/></el-select><el-button :loading="loading" @click="search">查询</el-button><el-button @click="load">刷新状态</el-button></div>
 <el-alert v-if="error&&!edit" :title="error" type="error" :closable="false"/>
 <div class="table-panel"><el-table :data="result?.items||[]" v-loading="loading"><el-table-column prop="title" label="标题" min-width="240"/><el-table-column label="宠物类型" min-width="110"><template #default="{row}">{{row.petType==='cat'?'猫':row.petType==='dog'?'狗':'猫和狗'}}</template></el-table-column><el-table-column label="发布状态" min-width="110"><template #default="{row}">{{row.status==='published'?'已发布':row.status==='draft'?'草稿':'已归档'}}</template></el-table-column><el-table-column label="回答可用状态" min-width="170"><template #default="{row}"><el-tag :type="row.indexStatus==='ready'?'success':row.indexStatus==='failed'?'danger':'info'">{{labels[row.indexStatus]||row.indexStatus}}</el-tag><p v-if="row.indexStatus==='failed'" class="small muted">请编辑并重新审核发布以重试。</p></template></el-table-column><el-table-column prop="version" label="版本" width="80"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click="open(row)">编辑</el-button></template></el-table-column></el-table><el-pagination v-if="result" v-model:current-page="pageNumber" :page-size="20" :total="result.total" layout="prev,pager,next" @current-change="load"/></div>
 <el-dialog v-model="edit" :title="selected?'编辑知识':'新建知识'" width="min(680px, 94vw)"><el-form label-position="top">
  <el-form-item label="标题"><el-input v-model="form.title" maxlength="120"/></el-form-item>
  <div class="form-grid"><el-form-item label="宠物类型"><el-select v-model="form.petType"><el-option value="dog" label="狗"/><el-option value="cat" label="猫"/><el-option value="both" label="猫和狗"/></el-select></el-form-item><el-form-item label="知识分类"><el-select v-model="form.category"><el-option v-for="c in [['feeding','饲养'],['breed','品种'],['training','训练'],['health','健康'],['grooming','美容']]" :key="c[0]" :value="c[0]" :label="c[1]"/></el-select></el-form-item></div>
  <el-form-item label="适用品种（可选）"><el-select v-model="form.breedNames" multiple filterable allow-create default-first-option :multiple-limit="20" placeholder="输入品种后按回车，留空表示不限品种"/></el-form-item>
  <el-form-item label="内容格式"><el-radio-group v-model="form.format"><el-radio value="article">文章</el-radio><el-radio value="qa">问答对</el-radio></el-radio-group></el-form-item>
  <el-form-item v-if="form.format==='article'" label="正文"><el-input v-model="form.content" type="textarea" :rows="5" maxlength="30000"/></el-form-item><template v-else><el-form-item label="问题"><el-input v-model="form.question" maxlength="2000"/></el-form-item><el-form-item label="答案"><el-input v-model="form.answer" type="textarea" :rows="5" maxlength="10000"/></el-form-item></template>
  <el-form-item label="来源名称"><el-input v-model="form.sourceName" maxlength="200" placeholder="例如：门店饲养手册"/></el-form-item><el-form-item label="公开来源链接（可选）"><el-input v-model="form.sourceUrl" maxlength="2048" placeholder="https://…"/></el-form-item>
  <el-form-item label="发布状态"><el-select v-model="form.status" @change="reviewed=false"><el-option value="draft" label="保存为草稿"/><el-option value="published" label="审核并发布"/><el-option value="archived" label="归档"/></el-select></el-form-item>
  <el-checkbox v-if="form.status==='published'" v-model="reviewed">我已审核内容和来源，确认可用于猫狗咨询</el-checkbox>
 </el-form><el-alert v-if="error" :title="error" type="error" :closable="false"/><template #footer><el-button @click="edit=false">取消</el-button><el-button type="primary" :loading="loading" :disabled="form.status==='published'&&!reviewed" @click="save">{{form.status==='published'?'确认发布':'保存知识'}}</el-button></template></el-dialog>
</template>
