<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {admin,upload} from '../../../shared/api'
import type {ShopSettings} from '../../../shared/adminTypes'
import {useLoad} from '../../../shared/useLoad'
import {ElMessage} from 'element-plus'
const form=ref<ShopSettings>(),{loading,error,run}=useLoad()
const load=()=>run(async()=>{form.value=await admin('GET','/admin/shop')})
// 保留完整配置与版本号，避免更新基础资料时丢失轮播设置。
const save=()=>run(async()=>{const {id,...body}=form.value!;form.value=await admin('PUT','/admin/shop',body);ElMessage.success('门店设置已保存')})
async function bannerImage(event:Event,index:number){const file=(event.target as HTMLInputElement).files?.[0];if(file)await run(async()=>{const asset=await upload('admin',file,'banner');form.value!.banners[index]!.imageFileId=asset.id})}
onMounted(load)
</script>
<template><div class="section-title"><div><p class="eyebrow">YOUR WARM LITTLE STORE</p><h2>把门店的温度，传递出去。</h2></div><el-button :loading="loading" @click="load">重新加载</el-button></div><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form v-if="form" label-position="top" class="table-panel" @submit.prevent="save"><div class="form-grid"><el-form-item label="门店名称"><el-input v-model="form.name" required maxlength="80"/></el-form-item><el-form-item label="营业时间"><el-input v-model="form.businessHours" required placeholder="每天 10:00-20:00"/><small>预约按北京时间校验，填写每天相同的营业时段。</small></el-form-item><el-form-item label="联系电话"><el-input v-model="form.phone" required/></el-form-item><el-form-item label="微信号"><el-input v-model="form.wechat" required/></el-form-item></div><el-form-item label="门店地址"><el-input v-model="form.address" required/></el-form-item><el-form-item label="到店自提说明"><el-input v-model="form.pickupInstructions" type="textarea" :rows="3"/></el-form-item><div class="form-grid"><el-form-item label="纬度"><el-input-number v-model="form.latitude" :min="-90" :max="90" :precision="6"/></el-form-item><el-form-item label="经度"><el-input-number v-model="form.longitude" :min="-180" :max="180" :precision="6"/></el-form-item><el-form-item label="历史订单付款保留时间（分钟）"><el-input-number v-model="form.paymentTimeoutMinutes" :min="5" :max="120"/></el-form-item><el-form-item label="历史订单自提保留时间（小时）"><el-input-number v-model="form.pickupRetentionHours" :min="1" :max="168"/></el-form-item></div><h3>首页轮播</h3><div v-for="(banner,index) in form.banners" :key="index" class="table-panel"><el-form-item label="标题"><el-input v-model="banner.title" required maxlength="80"/></el-form-item><p class="small muted">图片文件：{{banner.imageFileId||'请上传'}}</p><input type="file" accept="image/jpeg,image/png,image/webp" @change="bannerImage($event,index)"><el-form-item label="点击行为"><el-select v-model="banner.linkType" @change="banner.petId=null;banner.noticeText=null"><el-option value="none" label="无跳转"/><el-option value="pet" label="宠物详情"/><el-option value="notice" label="公告"/></el-select></el-form-item><el-input v-if="banner.linkType==='pet'" v-model="banner.petId" placeholder="宠物 ID"/><el-input v-if="banner.linkType==='notice'" v-model="banner.noticeText" type="textarea" placeholder="公告正文"/><el-checkbox v-model="banner.enabled">启用</el-checkbox><el-button link type="danger" @click="form.banners.splice(index,1)">移除</el-button></div><el-button :disabled="form.banners.length>=10" @click="form.banners.push({id:null,title:'',imageFileId:'',linkType:'none',petId:null,noticeText:null,sortOrder:form.banners.length,enabled:true})">添加轮播</el-button><p class="muted">预约规则：未来7天内；24小时内且不晚于到店时间确认；确认后保留到约定时间后2小时。</p><el-button type="primary" native-type="submit" size="large" :loading="loading">保存门店设置</el-button></el-form></template>
