spring:
  application:
    name: warmpaw-backend
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 101MB
  jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
app:
  storage: ${PAW_STORAGE:./data/files}
  admin-username: ${PAW_ADMIN_USERNAME:admin}
  admin-password: ${PAW_ADMIN_PASSWORD:}
  mock-providers: false
  redis-enabled: false
