export type PetStatus = 'off' | 'on_sale' | 'reserved' | 'sold'
export interface Page<T> { items: T[]; page: number; pageSize: number; total: number }
export interface Shop { id: string; name: string; address: string; phone: string; wechat: string; businessHours: string; pickupInstructions: string; latitude: number; longitude: number; coordinateSystem: string }
export interface Pet { id: string; name: string; category: 'cat' | 'dog'; breed: string; coverUrl: string; priceAmount: number; currency: string; gender: 'male' | 'female'; ageMonths: number; status: PetStatus; isRecommended: boolean; publishedAt: string; version: number; weightKg: number; color: string; personalityTags: string[]; vaccineStatus: string; dewormStatus: string; description: string; feedingNotes: string; healthDescription: string; images: {fileId: string; url: string; sortOrder: number}[]; videoUrl: string | null; quarantine: {certificateNo: string; images: {fileId: string; url: string}[]; validUntil: string | null; reviewStatus: string} | null; shop: Shop; purchaseAllowed: boolean; purchaseBlockedReason: string | null }
export interface Banner { id: string; title: string; imageUrl: string; linkType: 'pet' | 'notice' | 'none'; petId: string | null; noticeText: string | null }
export interface Category { code: string; name: string; breeds: string[] }
export interface HomeData { banners: Banner[]; categories: Category[]; recommendedPets: Pet[]; latestPets: Pet[]; shop: Shop }
export interface User { id: string; nickname: string; avatarUrl: string | null; phoneMasked: string }
export interface LoginResult { accessToken: string; expiresIn: number; user: User }
export interface Agreement { id: string; type: string; version: string; title: string; content: string; contentHash: string; healthGuaranteeDays: number | null }
export interface OrderPreview { product: Pet; productVersion: number; amount: number; shop: Shop; agreementVersion: string; agreementContentHash: string; purchaseAllowed: boolean; blockedReason: string | null; paymentTimeoutMinutes: number; pickupRetentionHours: number; healthGuaranteeDays: number }
export interface Order { id: string; orderNo: string; status: string; statusText: string; product: {id:string; name:string; breed:string; coverUrl:string}; amount: number; refundedAmount: number; createdAt: string; expiresAt: string; paidAt: string | null; pickupDeadlineAt: string | null; completedAt: string | null; availableActions: string[]; afterSaleStatus: string; shopSnapshot: Shop; contactName: string; contactPhoneMasked: string; remark: string; agreement: {title: string; content: string; version: string; signedAt: string}; pickup: {code: string; qrPayload: string; expiresAt: string; buyerConfirmedAt: string | null} | null; healthGuaranteeExpiresAt: string | null; afterSale: AfterSale | null; afterSaleEligibility: {allowedTypes: string[]; allowedResolutions: string[]; blockedReason: string | null}; refunds: {id: string; amount: number; status: string; failureReason: string | null}[] }
export interface AfterSale { id: string; orderId: string; status: string; type: string; requestedResolution: string; reason: string; createdAt: string; version?: number; reviewReason?: string; timeline?: {occurredAt: string; label: string; note: string | null}[]; diagnosisFileIds?: string[] }
export interface FileAsset { id: string; url?: string; fileName?: string; name?: string }
export interface Payment { status: string; scene: 'h5' | 'jsapi'; h5Url?: string; invokeParams?: Record<string,string>; orderStatus?: string; nextPollAfter?: number }
export interface Source { title: string; sourceName: string; sourceUrl: string | null; excerpt: string }
export interface AiMessage { id: string; role: 'user' | 'assistant'; content: string; status: string; sources?: Source[]; productCards?: Pet[]; orderCards?: {orderId: string; orderNo:string; status:string; productName:string; nextAction:string|null}[]; disclaimer?: string; actions?: {type: string; label: string; targetId?: string}[] }
